---
title: Artificial Intelligence in the diagnosis of orthopaedic conditions (Bone Tumours and Infection)
author: Anais
date: '2022-07-21'
slug: artificial-intelligence-in-the-diagnosis-of-orthopaedic-conditions
categories: []
weight:
tags: 
 - Biology
 - Current projects
subtitle: ''
summary: 'Funded by the RJAH Orthopaedic and District...'
authors: ["Karina Wright","Paul Cool","Helen McCarthy","Jade Perry","Hollie Wilkinson"]
lastmod: '2022-07-21T20:24:56+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
**PhD project**:"Artificial Intelligence in the diagnosis of orthopaedic conditions"

Supervisors: Dr Karina Wright and Dr Paul Cool


The aim of this PhD prpject is o investigate the possibility of using nanopore DNA sequencing technology for the real time identification of pathogens in infected arthroplasty, including antimicrobial resistance.

With the lack of a gold standard for identifying infected arthroplasty, comparison will be made with results from frozen section histology, microbiological cultures, clinical details and results from laboratory tests (CRP, ESR, WCC etc).

Artificial intelligence models will be tested on the frozen section histology slides to compare with clinical results to investigate if more accurate predictions can be made on frozen section histology. 
