---
title: Anaïs Makos
author: ''
date: '2021-05-13'
slug: anaïs-makos
lastmod: '2021-05-13T15:49:22+01:00'
role: PhD Student
bio: I am a PhD student at Keele University, in the Rheumatology Research department based at RJAH, Oswestry.
interests:
  - Psoriatic Arthritis
  - Inflammation
  - Cell biology and Immunology 
  - Immunotherapy
email: a.makos@keele.ac.uk
highlight_name: true
superuser: false
user_groups:
  - Researchers
organizations:
  - name: Keele University
    url: 'https://www.keele.ac.uk/pharmacy-bioengineering/'
education:
  courses:
    - course: BSc in Life Sciences – Molecular biology and Biochemistry
      institution: University of Lorraine, France
      year: 2017
    - course: MSc in Biosciences and Health engineering – Biotechnology and Cell engineering
      institution: University of Lorraine, France
      year: 2019
    - course: PhD in Cell and Tissue Engineering
      institution: University of Keele, UK
      year: 2020-2024
social:
  - icon: envelope
    icon_pack: fas
    link: mailto:a.makos@keele.ac.uk
---
I am a PhD student at Keele University, in the Rheumatology Research department based at RJAH, Oswestry.

I study Psoriatic Arthritis (PsA), a chronic immune-mediated inflammatory disease characterized by widespread musculoskeletal inflammation, which affects approximately 30% of patients with psoriasis. Currently, PsA patients are treated with Non Steroidal Anti-Inflammatory drugs (NSAID) used as first approach for topical therapy for psoriasis and to reduce pain. The next step is the administration of Disease-Modifying Anti-Rheumatic Drugs (DMARDs) alone, and then in combination. Finally, biologic drugs such as Tumor Necrosis Factor α (TNFα) inhibitors or Interleukin-17 (IL-17) inhibitors are administered if patients fail to respond NSAID and DMARDs. Nevertheless, about 40% of PsA patients only partially respond or fail to respond to biologic treatments.
I am working on a clinical project in order to find biomarkers that will predict if PsA patients will respond or will not respond to anti-TNFα treatment. The main objectives of my work are:

- Find biomarkers in literature research that could predict the response of patients to TNFα inhibitors;
- Get the consent of patients with PsA in order to collect a blood sample before and after treatment; 
- Verify if biomarkers found in literature research can predict patient response in the blood samples. 
