---
title: Human chondrocytes expanded in the Quantum速 hollow-fibre bioreactor system
  for the first time
author: 'John Garcia'
date: '2021-04-28'
slug: human-chondrocytes-expanded-in-the-quantum-hollow-fibre-bioreactor-system-for-the-first-time
categories: []
tags:
  - Bioreactor
  - Arthritis
subtitle: ''
summary: ''
authors: ["John Garcia", "Charlotte Hulme", "Claire Mennan", "Sally Roberts", "Karina Wright"]
lastmod: '2021-04-28T16:07:04+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
links:
- icon: twitter
  icon_pack: fab
  name: Follow
  url: https://twitter.com/CellTherapyRJAH
- icon: hand-holding-usd
  icon_pack: fas
  name: Funder 1
  url: https://mrc.ukri.org/
- icon: hand-holding-usd
  icon_pack: fas
  name: Funder 2
  url: https://www.versusarthritis.org/
---

The Quantum速 bioreactor (Fig 9; Terumo BCT) is an automated hollow fibre system, which has an internal surface area of 2.1m$^2$ (equivalent to 120 T-175 tissue culture flasks), allowing large scale expansion of cells.  
In recently published work we have been using the Quantum速 to assess the characteristics of cells from human bone marrow and umbilical cords after culture expansion in the system compared to the standard tissue culture plastic technique (TCP), with the aim of using these cells in cell therapies for example, for cartilage repair.  
In a newly funded 'Confidence in Concept' MRC project we have looked to transfer these techniques to cells of cartilage (chondrocytes), in the development of up-scale manufactured allogeneic chondrocyte therapies.

So far cells from 4 samples obtained from adult donors (undergoing total knee replacements) and 2 samples obtained from juvenile (polydactyl) donors have been cultured in the Quantum速 and the results are currently being analysed. 
Techniques for chondrocyte growth and harvest using the system are being optimised and further MRC Biomedical Catalyst funded work will ensure GMP compliance of the manufacturing process.
