---
title: Advancing Osteochondral Tissue Supply Chain Transport Conditions for Clinical
  Allografts
author: anais
date: '2022-07-21'
slug: advancing-osteochondral-tissue-supply-chain-transport-conditions-for-clinical-allografts-and-advanced-therapy-medicinal-products
categories: []
tags:
  - Future projects
subtitle: ''
summary: 'Funded by'
authors: []
lastmod: '2022-07-21T10:44:41+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
links:
- icon: Calendar
  icon_pack: fas
  name: Apply here
  url: https://www.findaphd.com/phds/project/advancing-osteochondral-tissue-supply-chain-transport-conditions-for-clinical-allografts-and-advanced-therapy-medicinal-products/?p145925
---
**PhD project**: "Advancing Osteochondral Tissue Supply Chain Transport Conditions for Clinical Allografts and Advanced Therapy Medicinal Products"

Application open until Friday, August 12, 2022

Supervisors: Dr Karina Wright and Prof Martyn Snow


Fresh Osteochondral allograft (OCA) involves the implantation of donor cartilage and bone in a one-step procedure to treat large osteochondral defects. The treatment has principally been pioneered in North America over the last 20 years, with the majority of the excellent long-term results published in centres with local tissue banks. OCA must be implanted within 28 days of harvest in order to maintain cartilage cell viability above 70%, the level at which has been shown to correlate with good clinical outcomes in animal studies. Consequently, there is a short time-frame for graft implantation following processing (usually 2-weeks) which limits graft availability and utilisation.

The early success of OCA has resulted in the technique being utilised in many centres across the world. Consequently, OCA grafts are being transported via air over long distances for extended periods. Recent published data along with data from our preliminary investigations has shown that the viability of clinical OCA is well below industry standards. The individual and combined influences of supply chain transport conditions on cell viability is unknown. There is concern over the potential for cell death as a consequence of adverse temperature and pressures experienced by the grafts in the cargo hold. There is also the potential for additional cell death due to radiation exposure (5-6 times the radiation of a chest X-ray).

The project will involve a comprehensive study to investigate the effect of prolonged transport on allograft chondrocyte viability and the potential benefits of transport using alternative media/conditions. The aim is to optimise the storage and delivery of OCA and to explore the cryopreservation of grafts in order to prolong cell viability and increase graft availability for surgical use and as a source of cells for new cell-based therapies.

The successful applicant will work closely within a multi-disciplinary team across a number of specialties and collaboratively with US industry partners. In this way we will provide a solution to an urgent clinical problem which will have a potential major and quickly realised impact on the quality of life of patients.

This project provides the opportunity to work closely with clinicians, patients and samples/data to address a pertinent clinical problem that will likely lead to patient benefit. The successful applicant will be expected to communicate with patients and surgeons, take consent and obtain samples in the operating theatre. The studentship will be based at the RJAH Orthopaedic Hospital in Oswestry. However, there will be the occasional need to attend training at Keele University. 
